// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mes.proto

package com.lirunlong.mes;

public final class Mes {
  private Mes() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TestMesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TestMes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string mes = 1;</code>
     */
    java.lang.String getMes();
    /**
     * <code>string mes = 1;</code>
     */
    com.google.protobuf.ByteString
        getMesBytes();

    /**
     * <code>int32 mesId = 2;</code>
     */
    int getMesId();
  }
  /**
   * Protobuf type {@code TestMes}
   */
  public  static final class TestMes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TestMes)
      TestMesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TestMes.newBuilder() to construct.
    private TestMes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TestMes() {
      mes_ = "";
      mesId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TestMes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              mes_ = s;
              break;
            }
            case 16: {

              mesId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lirunlong.mes.Mes.internal_static_TestMes_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lirunlong.mes.Mes.internal_static_TestMes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lirunlong.mes.Mes.TestMes.class, com.lirunlong.mes.Mes.TestMes.Builder.class);
    }

    public static final int MES_FIELD_NUMBER = 1;
    private volatile java.lang.Object mes_;
    /**
     * <code>string mes = 1;</code>
     */
    public java.lang.String getMes() {
      java.lang.Object ref = mes_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mes_ = s;
        return s;
      }
    }
    /**
     * <code>string mes = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMesBytes() {
      java.lang.Object ref = mes_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESID_FIELD_NUMBER = 2;
    private int mesId_;
    /**
     * <code>int32 mesId = 2;</code>
     */
    public int getMesId() {
      return mesId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMesBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mes_);
      }
      if (mesId_ != 0) {
        output.writeInt32(2, mesId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMesBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, mes_);
      }
      if (mesId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, mesId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lirunlong.mes.Mes.TestMes)) {
        return super.equals(obj);
      }
      com.lirunlong.mes.Mes.TestMes other = (com.lirunlong.mes.Mes.TestMes) obj;

      boolean result = true;
      result = result && getMes()
          .equals(other.getMes());
      result = result && (getMesId()
          == other.getMesId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MES_FIELD_NUMBER;
      hash = (53 * hash) + getMes().hashCode();
      hash = (37 * hash) + MESID_FIELD_NUMBER;
      hash = (53 * hash) + getMesId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lirunlong.mes.Mes.TestMes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lirunlong.mes.Mes.TestMes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lirunlong.mes.Mes.TestMes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lirunlong.mes.Mes.TestMes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lirunlong.mes.Mes.TestMes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lirunlong.mes.Mes.TestMes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lirunlong.mes.Mes.TestMes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lirunlong.mes.Mes.TestMes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lirunlong.mes.Mes.TestMes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.lirunlong.mes.Mes.TestMes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lirunlong.mes.Mes.TestMes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lirunlong.mes.Mes.TestMes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lirunlong.mes.Mes.TestMes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TestMes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TestMes)
        com.lirunlong.mes.Mes.TestMesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lirunlong.mes.Mes.internal_static_TestMes_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lirunlong.mes.Mes.internal_static_TestMes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lirunlong.mes.Mes.TestMes.class, com.lirunlong.mes.Mes.TestMes.Builder.class);
      }

      // Construct using com.lirunlong.mes.Mes.TestMes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        mes_ = "";

        mesId_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lirunlong.mes.Mes.internal_static_TestMes_descriptor;
      }

      public com.lirunlong.mes.Mes.TestMes getDefaultInstanceForType() {
        return com.lirunlong.mes.Mes.TestMes.getDefaultInstance();
      }

      public com.lirunlong.mes.Mes.TestMes build() {
        com.lirunlong.mes.Mes.TestMes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lirunlong.mes.Mes.TestMes buildPartial() {
        com.lirunlong.mes.Mes.TestMes result = new com.lirunlong.mes.Mes.TestMes(this);
        result.mes_ = mes_;
        result.mesId_ = mesId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lirunlong.mes.Mes.TestMes) {
          return mergeFrom((com.lirunlong.mes.Mes.TestMes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lirunlong.mes.Mes.TestMes other) {
        if (other == com.lirunlong.mes.Mes.TestMes.getDefaultInstance()) return this;
        if (!other.getMes().isEmpty()) {
          mes_ = other.mes_;
          onChanged();
        }
        if (other.getMesId() != 0) {
          setMesId(other.getMesId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lirunlong.mes.Mes.TestMes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lirunlong.mes.Mes.TestMes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object mes_ = "";
      /**
       * <code>string mes = 1;</code>
       */
      public java.lang.String getMes() {
        java.lang.Object ref = mes_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mes_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string mes = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMesBytes() {
        java.lang.Object ref = mes_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mes_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mes = 1;</code>
       */
      public Builder setMes(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string mes = 1;</code>
       */
      public Builder clearMes() {
        
        mes_ = getDefaultInstance().getMes();
        onChanged();
        return this;
      }
      /**
       * <code>string mes = 1;</code>
       */
      public Builder setMesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mes_ = value;
        onChanged();
        return this;
      }

      private int mesId_ ;
      /**
       * <code>int32 mesId = 2;</code>
       */
      public int getMesId() {
        return mesId_;
      }
      /**
       * <code>int32 mesId = 2;</code>
       */
      public Builder setMesId(int value) {
        
        mesId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 mesId = 2;</code>
       */
      public Builder clearMesId() {
        
        mesId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TestMes)
    }

    // @@protoc_insertion_point(class_scope:TestMes)
    private static final com.lirunlong.mes.Mes.TestMes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lirunlong.mes.Mes.TestMes();
    }

    public static com.lirunlong.mes.Mes.TestMes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TestMes>
        PARSER = new com.google.protobuf.AbstractParser<TestMes>() {
      public TestMes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TestMes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TestMes> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TestMes> getParserForType() {
      return PARSER;
    }

    public com.lirunlong.mes.Mes.TestMes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CubeRotationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CubeRotation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Vector3 vector3 = 1;</code>
     */
    boolean hasVector3();
    /**
     * <code>.Vector3 vector3 = 1;</code>
     */
    com.lirunlong.mes.Mes.Vector3 getVector3();
    /**
     * <code>.Vector3 vector3 = 1;</code>
     */
    com.lirunlong.mes.Mes.Vector3OrBuilder getVector3OrBuilder();
  }
  /**
   * Protobuf type {@code CubeRotation}
   */
  public  static final class CubeRotation extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CubeRotation)
      CubeRotationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CubeRotation.newBuilder() to construct.
    private CubeRotation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CubeRotation() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CubeRotation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.lirunlong.mes.Mes.Vector3.Builder subBuilder = null;
              if (vector3_ != null) {
                subBuilder = vector3_.toBuilder();
              }
              vector3_ = input.readMessage(com.lirunlong.mes.Mes.Vector3.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(vector3_);
                vector3_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lirunlong.mes.Mes.internal_static_CubeRotation_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lirunlong.mes.Mes.internal_static_CubeRotation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lirunlong.mes.Mes.CubeRotation.class, com.lirunlong.mes.Mes.CubeRotation.Builder.class);
    }

    public static final int VECTOR3_FIELD_NUMBER = 1;
    private com.lirunlong.mes.Mes.Vector3 vector3_;
    /**
     * <code>.Vector3 vector3 = 1;</code>
     */
    public boolean hasVector3() {
      return vector3_ != null;
    }
    /**
     * <code>.Vector3 vector3 = 1;</code>
     */
    public com.lirunlong.mes.Mes.Vector3 getVector3() {
      return vector3_ == null ? com.lirunlong.mes.Mes.Vector3.getDefaultInstance() : vector3_;
    }
    /**
     * <code>.Vector3 vector3 = 1;</code>
     */
    public com.lirunlong.mes.Mes.Vector3OrBuilder getVector3OrBuilder() {
      return getVector3();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (vector3_ != null) {
        output.writeMessage(1, getVector3());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (vector3_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getVector3());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lirunlong.mes.Mes.CubeRotation)) {
        return super.equals(obj);
      }
      com.lirunlong.mes.Mes.CubeRotation other = (com.lirunlong.mes.Mes.CubeRotation) obj;

      boolean result = true;
      result = result && (hasVector3() == other.hasVector3());
      if (hasVector3()) {
        result = result && getVector3()
            .equals(other.getVector3());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasVector3()) {
        hash = (37 * hash) + VECTOR3_FIELD_NUMBER;
        hash = (53 * hash) + getVector3().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lirunlong.mes.Mes.CubeRotation parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lirunlong.mes.Mes.CubeRotation parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lirunlong.mes.Mes.CubeRotation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lirunlong.mes.Mes.CubeRotation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lirunlong.mes.Mes.CubeRotation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lirunlong.mes.Mes.CubeRotation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lirunlong.mes.Mes.CubeRotation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lirunlong.mes.Mes.CubeRotation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lirunlong.mes.Mes.CubeRotation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.lirunlong.mes.Mes.CubeRotation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lirunlong.mes.Mes.CubeRotation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lirunlong.mes.Mes.CubeRotation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lirunlong.mes.Mes.CubeRotation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CubeRotation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CubeRotation)
        com.lirunlong.mes.Mes.CubeRotationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lirunlong.mes.Mes.internal_static_CubeRotation_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lirunlong.mes.Mes.internal_static_CubeRotation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lirunlong.mes.Mes.CubeRotation.class, com.lirunlong.mes.Mes.CubeRotation.Builder.class);
      }

      // Construct using com.lirunlong.mes.Mes.CubeRotation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (vector3Builder_ == null) {
          vector3_ = null;
        } else {
          vector3_ = null;
          vector3Builder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lirunlong.mes.Mes.internal_static_CubeRotation_descriptor;
      }

      public com.lirunlong.mes.Mes.CubeRotation getDefaultInstanceForType() {
        return com.lirunlong.mes.Mes.CubeRotation.getDefaultInstance();
      }

      public com.lirunlong.mes.Mes.CubeRotation build() {
        com.lirunlong.mes.Mes.CubeRotation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lirunlong.mes.Mes.CubeRotation buildPartial() {
        com.lirunlong.mes.Mes.CubeRotation result = new com.lirunlong.mes.Mes.CubeRotation(this);
        if (vector3Builder_ == null) {
          result.vector3_ = vector3_;
        } else {
          result.vector3_ = vector3Builder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lirunlong.mes.Mes.CubeRotation) {
          return mergeFrom((com.lirunlong.mes.Mes.CubeRotation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lirunlong.mes.Mes.CubeRotation other) {
        if (other == com.lirunlong.mes.Mes.CubeRotation.getDefaultInstance()) return this;
        if (other.hasVector3()) {
          mergeVector3(other.getVector3());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lirunlong.mes.Mes.CubeRotation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lirunlong.mes.Mes.CubeRotation) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.lirunlong.mes.Mes.Vector3 vector3_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.lirunlong.mes.Mes.Vector3, com.lirunlong.mes.Mes.Vector3.Builder, com.lirunlong.mes.Mes.Vector3OrBuilder> vector3Builder_;
      /**
       * <code>.Vector3 vector3 = 1;</code>
       */
      public boolean hasVector3() {
        return vector3Builder_ != null || vector3_ != null;
      }
      /**
       * <code>.Vector3 vector3 = 1;</code>
       */
      public com.lirunlong.mes.Mes.Vector3 getVector3() {
        if (vector3Builder_ == null) {
          return vector3_ == null ? com.lirunlong.mes.Mes.Vector3.getDefaultInstance() : vector3_;
        } else {
          return vector3Builder_.getMessage();
        }
      }
      /**
       * <code>.Vector3 vector3 = 1;</code>
       */
      public Builder setVector3(com.lirunlong.mes.Mes.Vector3 value) {
        if (vector3Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          vector3_ = value;
          onChanged();
        } else {
          vector3Builder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Vector3 vector3 = 1;</code>
       */
      public Builder setVector3(
          com.lirunlong.mes.Mes.Vector3.Builder builderForValue) {
        if (vector3Builder_ == null) {
          vector3_ = builderForValue.build();
          onChanged();
        } else {
          vector3Builder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Vector3 vector3 = 1;</code>
       */
      public Builder mergeVector3(com.lirunlong.mes.Mes.Vector3 value) {
        if (vector3Builder_ == null) {
          if (vector3_ != null) {
            vector3_ =
              com.lirunlong.mes.Mes.Vector3.newBuilder(vector3_).mergeFrom(value).buildPartial();
          } else {
            vector3_ = value;
          }
          onChanged();
        } else {
          vector3Builder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Vector3 vector3 = 1;</code>
       */
      public Builder clearVector3() {
        if (vector3Builder_ == null) {
          vector3_ = null;
          onChanged();
        } else {
          vector3_ = null;
          vector3Builder_ = null;
        }

        return this;
      }
      /**
       * <code>.Vector3 vector3 = 1;</code>
       */
      public com.lirunlong.mes.Mes.Vector3.Builder getVector3Builder() {
        
        onChanged();
        return getVector3FieldBuilder().getBuilder();
      }
      /**
       * <code>.Vector3 vector3 = 1;</code>
       */
      public com.lirunlong.mes.Mes.Vector3OrBuilder getVector3OrBuilder() {
        if (vector3Builder_ != null) {
          return vector3Builder_.getMessageOrBuilder();
        } else {
          return vector3_ == null ?
              com.lirunlong.mes.Mes.Vector3.getDefaultInstance() : vector3_;
        }
      }
      /**
       * <code>.Vector3 vector3 = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.lirunlong.mes.Mes.Vector3, com.lirunlong.mes.Mes.Vector3.Builder, com.lirunlong.mes.Mes.Vector3OrBuilder> 
          getVector3FieldBuilder() {
        if (vector3Builder_ == null) {
          vector3Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.lirunlong.mes.Mes.Vector3, com.lirunlong.mes.Mes.Vector3.Builder, com.lirunlong.mes.Mes.Vector3OrBuilder>(
                  getVector3(),
                  getParentForChildren(),
                  isClean());
          vector3_ = null;
        }
        return vector3Builder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CubeRotation)
    }

    // @@protoc_insertion_point(class_scope:CubeRotation)
    private static final com.lirunlong.mes.Mes.CubeRotation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lirunlong.mes.Mes.CubeRotation();
    }

    public static com.lirunlong.mes.Mes.CubeRotation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CubeRotation>
        PARSER = new com.google.protobuf.AbstractParser<CubeRotation>() {
      public CubeRotation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CubeRotation(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CubeRotation> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CubeRotation> getParserForType() {
      return PARSER;
    }

    public com.lirunlong.mes.Mes.CubeRotation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Vector3OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Vector3)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float x = 1;</code>
     */
    float getX();

    /**
     * <code>float y = 2;</code>
     */
    float getY();

    /**
     * <code>float z = 3;</code>
     */
    float getZ();
  }
  /**
   * Protobuf type {@code Vector3}
   */
  public  static final class Vector3 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Vector3)
      Vector3OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Vector3.newBuilder() to construct.
    private Vector3(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Vector3() {
      x_ = 0F;
      y_ = 0F;
      z_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Vector3(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {

              x_ = input.readFloat();
              break;
            }
            case 21: {

              y_ = input.readFloat();
              break;
            }
            case 29: {

              z_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lirunlong.mes.Mes.internal_static_Vector3_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lirunlong.mes.Mes.internal_static_Vector3_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lirunlong.mes.Mes.Vector3.class, com.lirunlong.mes.Mes.Vector3.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1;
    private float x_;
    /**
     * <code>float x = 1;</code>
     */
    public float getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private float y_;
    /**
     * <code>float y = 2;</code>
     */
    public float getY() {
      return y_;
    }

    public static final int Z_FIELD_NUMBER = 3;
    private float z_;
    /**
     * <code>float z = 3;</code>
     */
    public float getZ() {
      return z_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (x_ != 0F) {
        output.writeFloat(1, x_);
      }
      if (y_ != 0F) {
        output.writeFloat(2, y_);
      }
      if (z_ != 0F) {
        output.writeFloat(3, z_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (x_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, x_);
      }
      if (y_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, y_);
      }
      if (z_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, z_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lirunlong.mes.Mes.Vector3)) {
        return super.equals(obj);
      }
      com.lirunlong.mes.Mes.Vector3 other = (com.lirunlong.mes.Mes.Vector3) obj;

      boolean result = true;
      result = result && (
          java.lang.Float.floatToIntBits(getX())
          == java.lang.Float.floatToIntBits(
              other.getX()));
      result = result && (
          java.lang.Float.floatToIntBits(getY())
          == java.lang.Float.floatToIntBits(
              other.getY()));
      result = result && (
          java.lang.Float.floatToIntBits(getZ())
          == java.lang.Float.floatToIntBits(
              other.getZ()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getX());
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getY());
      hash = (37 * hash) + Z_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getZ());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lirunlong.mes.Mes.Vector3 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lirunlong.mes.Mes.Vector3 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lirunlong.mes.Mes.Vector3 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lirunlong.mes.Mes.Vector3 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lirunlong.mes.Mes.Vector3 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lirunlong.mes.Mes.Vector3 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lirunlong.mes.Mes.Vector3 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lirunlong.mes.Mes.Vector3 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lirunlong.mes.Mes.Vector3 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.lirunlong.mes.Mes.Vector3 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lirunlong.mes.Mes.Vector3 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lirunlong.mes.Mes.Vector3 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lirunlong.mes.Mes.Vector3 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Vector3}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Vector3)
        com.lirunlong.mes.Mes.Vector3OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lirunlong.mes.Mes.internal_static_Vector3_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lirunlong.mes.Mes.internal_static_Vector3_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lirunlong.mes.Mes.Vector3.class, com.lirunlong.mes.Mes.Vector3.Builder.class);
      }

      // Construct using com.lirunlong.mes.Mes.Vector3.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        x_ = 0F;

        y_ = 0F;

        z_ = 0F;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lirunlong.mes.Mes.internal_static_Vector3_descriptor;
      }

      public com.lirunlong.mes.Mes.Vector3 getDefaultInstanceForType() {
        return com.lirunlong.mes.Mes.Vector3.getDefaultInstance();
      }

      public com.lirunlong.mes.Mes.Vector3 build() {
        com.lirunlong.mes.Mes.Vector3 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lirunlong.mes.Mes.Vector3 buildPartial() {
        com.lirunlong.mes.Mes.Vector3 result = new com.lirunlong.mes.Mes.Vector3(this);
        result.x_ = x_;
        result.y_ = y_;
        result.z_ = z_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lirunlong.mes.Mes.Vector3) {
          return mergeFrom((com.lirunlong.mes.Mes.Vector3)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lirunlong.mes.Mes.Vector3 other) {
        if (other == com.lirunlong.mes.Mes.Vector3.getDefaultInstance()) return this;
        if (other.getX() != 0F) {
          setX(other.getX());
        }
        if (other.getY() != 0F) {
          setY(other.getY());
        }
        if (other.getZ() != 0F) {
          setZ(other.getZ());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lirunlong.mes.Mes.Vector3 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lirunlong.mes.Mes.Vector3) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float x_ ;
      /**
       * <code>float x = 1;</code>
       */
      public float getX() {
        return x_;
      }
      /**
       * <code>float x = 1;</code>
       */
      public Builder setX(float value) {
        
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float x = 1;</code>
       */
      public Builder clearX() {
        
        x_ = 0F;
        onChanged();
        return this;
      }

      private float y_ ;
      /**
       * <code>float y = 2;</code>
       */
      public float getY() {
        return y_;
      }
      /**
       * <code>float y = 2;</code>
       */
      public Builder setY(float value) {
        
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float y = 2;</code>
       */
      public Builder clearY() {
        
        y_ = 0F;
        onChanged();
        return this;
      }

      private float z_ ;
      /**
       * <code>float z = 3;</code>
       */
      public float getZ() {
        return z_;
      }
      /**
       * <code>float z = 3;</code>
       */
      public Builder setZ(float value) {
        
        z_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float z = 3;</code>
       */
      public Builder clearZ() {
        
        z_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Vector3)
    }

    // @@protoc_insertion_point(class_scope:Vector3)
    private static final com.lirunlong.mes.Mes.Vector3 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lirunlong.mes.Mes.Vector3();
    }

    public static com.lirunlong.mes.Mes.Vector3 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Vector3>
        PARSER = new com.google.protobuf.AbstractParser<Vector3>() {
      public Vector3 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Vector3(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Vector3> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Vector3> getParserForType() {
      return PARSER;
    }

    public com.lirunlong.mes.Mes.Vector3 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TestMes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TestMes_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CubeRotation_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CubeRotation_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Vector3_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Vector3_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tmes.proto\"%\n\007TestMes\022\013\n\003mes\030\001 \001(\t\022\r\n\005m" +
      "esId\030\002 \001(\005\")\n\014CubeRotation\022\031\n\007vector3\030\001 " +
      "\001(\0132\010.Vector3\"*\n\007Vector3\022\t\n\001x\030\001 \001(\002\022\t\n\001y" +
      "\030\002 \001(\002\022\t\n\001z\030\003 \001(\002B\023\n\021com.lirunlong.mesb\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TestMes_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TestMes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TestMes_descriptor,
        new java.lang.String[] { "Mes", "MesId", });
    internal_static_CubeRotation_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CubeRotation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CubeRotation_descriptor,
        new java.lang.String[] { "Vector3", });
    internal_static_Vector3_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Vector3_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Vector3_descriptor,
        new java.lang.String[] { "X", "Y", "Z", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
